name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #TODO: Step 1 - Add the rFlutter Alert package as a dependency here and use "Packages get".
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

